//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racks_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rack_inventory
    {
        public int R_id { get; set; }
        public string R_desc { get; set; }
        public int R_capacity { get; set; }
        public string R_status { get; set; }
    }
}
